# Null Model Comparison Experiment 1

In [1]:
import networkx as nx
import pandas as pd
import os
import random
from functools import reduce
import numpy as np

In [52]:
df = pd.read_csv('stuff/Directed_Weighted_Random_Null_Model_0_cascades.csv')

In [53]:
df.head()

,Unnamed: 0,liberal_average_activation_time,conservative_average_activation_time,ndp_average_activation_time,lgbt_average_activation_time,bloq_average_activation_time
0,16014404,NaN,NaN,NaN,NaN,0.0
1,20199202,NaN,1.0,NaN,NaN,NaN
2,22849568,0.0,NaN,NaN,NaN,NaN
3,23491400,1.0,NaN,NaN,NaN,NaN
4,24990450,NaN,NaN,NaN,NaN,2.0

In [54]:
df = df.set_index('Unnamed: 0')

In [55]:
df_lib = df[['liberal_average_activation_time']]
df_con = df[['conservative_average_activation_time']]
df_ndp = df[['ndp_average_activation_time']]
df_lgbt = df[['lgbt_average_activation_time']]
df_bloc = df[['bloq_average_activation_time']]

In [56]:
df_lib

                     liberal_average_activation_time
Unnamed: 0
16014404                                         NaN
20199202                                         NaN
22849568                                         0.0
23491400                                         1.0
24990450                                         NaN
29754743                                         1.0
40550119                                         NaN
44070432                                         2.0
59686058                                         NaN
85428184                                         1.0
119925381                                        NaN
196717787                                        NaN
211564038                                        NaN
271073165                                        NaN
294660973                                        NaN
377588094                                        3.0
412708728                                        2.0
2555308646                                       1.0
2715275551                                       NaN
2891740872                                       0.0
720083863830069249                               2.0
737359208945844224                               NaN
989311745100566529                               NaN
1063494232126689280                              NaN
1086084557009575936                              NaN
1125543746697924609                              1.0
1170770038208565248                              NaN
1382491059247255554                              1.0

In [27]:
df_lib.rename(columns={"liberal_average_activation_time": "liberal_average_activation_time1"})

                     liberal_average_activation_time1
Unnamed: 0
16014404                                          NaN
20199202                                          NaN
22849568                                          0.0
23491400                                          1.0
24990450                                          NaN
29754743                                          1.0
40550119                                          NaN
44070432                                          2.0
59686058                                          NaN
85428184                                          1.0
119925381                                         NaN
196717787                                         NaN
211564038                                         NaN
271073165                                         NaN
294660973                                         NaN
377588094                                         3.0
412708728                                         2.0
2555308646                                        1.0
2715275551                                        NaN
2891740872                                        0.0
720083863830069249                                2.0
737359208945844224                                NaN
989311745100566529                                NaN
1063494232126689280                               NaN
1086084557009575936                               NaN
1125543746697924609                               1.0
1170770038208565248                               NaN
1382491059247255554                               1.0

In [57]:
dirname="stuff"
directory = os.fsencode(dirname)
i =2
for file in os.listdir(directory):
    i = i +1
    filename = os.fsdecode(file)
    
    df = pd.read_csv(dirname+"/"+filename)
    df = df.set_index('Unnamed: 0')
    df_lib_1 = df[['liberal_average_activation_time']]
    df_lib_1 = df_lib_1.rename(columns={"liberal_average_activation_time": "liberal_average_activation_time{}".format(i)})
    df_con_1 = df[['conservative_average_activation_time']]
    df_con_1 = df_con_1.rename(columns={"conservative_average_activation_time": "conservative_average_activation_time{}".format(i)})
    df_ndp_1 = df[['ndp_average_activation_time']]
    df_ndp_1 = df_ndp_1.rename(columns={"ndp_average_activation_time": "ndp_average_activation_time{}".format(i)})
    df_lgbt_1 = df[['lgbt_average_activation_time']]
    df_lgbt_1 = df_lgbt_1.rename(columns={"lgbt_average_activation_time": "lgbt_average_activation_time{}".format(i)})
    df_bloc_1 = df[['bloq_average_activation_time']]
    df_bloc_1 = df_bloc_1.rename(columns={"bloq_average_activation_time": "bloq_average_activation_time{}".format(i)})
    
    #Perform an outer join on each df with their corresponding df
    
    df_lib = pd.merge(df_lib, df_lib_1, how="outer", right_index=True, left_index=True)
    df_con = pd.merge(df_con, df_con_1, how="outer", right_index=True, left_index=True)
    df_ndp = pd.merge(df_ndp, df_ndp_1, how="outer", right_index=True, left_index=True)
    df_lgbt = pd.merge(df_lgbt, df_lgbt_1, how="outer", right_index=True, left_index=True)
    df_bloc = pd.merge(df_bloc, df_bloc_1, how="outer", right_index=True, left_index=True)

In [58]:
df_lib.describe()

,liberal_average_activation_time,liberal_average_activation_time3,liberal_average_activation_time4,liberal_average_activation_time5,liberal_average_activation_time6,liberal_average_activation_time7,liberal_average_activation_time8,liberal_average_activation_time9,liberal_average_activation_time10,liberal_average_activation_time11,...,liberal_average_activation_time993,liberal_average_activation_time994,liberal_average_activation_time995,liberal_average_activation_time996,liberal_average_activation_time997,liberal_average_activation_time998,liberal_average_activation_time999,liberal_average_activation_time1000,liberal_average_activation_time1001,liberal_average_activation_time1002
count,12.000000,12.000000,10.000000,9.000000,9.000000,8.00000,9.000000,9.000000,10.000000,9.000000,...,11.000000,12.000000,8.00000,8.00000,10.000000,8.00000,9.000000,7.000000,7.000000,11.000000
mean,1.250000,1.250000,1.000000,0.888889,0.888889,0.75000,0.888889,0.888889,1.000000,0.888889,...,1.090909,1.166667,0.75000,0.87500,1.000000,0.75000,1.000000,0.714286,0.714286,1.090909
std,0.866025,0.866025,0.666667,0.600925,0.600925,0.46291,0.600925,0.600925,0.666667,0.600925,...,0.700649,0.717741,0.46291,0.64087,0.666667,0.46291,0.707107,0.487950,0.487950,0.700649
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,0.75000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.75000,0.75000,1.000000,0.75000,1.000000,0.500000,0.500000,1.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.00000,1.00000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000
75%,2.000000,2.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.500000,2.000000,1.00000,1.00000,1.000000,1.00000,1.000000,1.000000,1.000000,1.500000
max,3.000000,3.000000,2.000000,2.000000,2.000000,1.00000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,1.00000,2.00000,2.000000,1.00000,2.000000,1.000000,1.000000,2.000000

## Take an average of the count of each column

In [50]:
c = 0

c = c +df_lib['liberal_average_activation_time1002'].count()

In [51]:
df_lib['liberal_average_activation_time1002'].count()

11

Calculate the average number of nodes in a cascade

In [59]:
def count_nodes_per_cascade(df):
    lst = []
    for column in df:
        lst.append(df[column].count())
    return lst


def avg_nodes_per_cascade(df):
    count = 0;
    i
    for column in df:
        i=i+1
        count = count + df[column].count()
    return count / i

In [62]:
lib_count = np.array(count_nodes_per_cascade(df_lib))

In [63]:
lib_count

array([12, 12, 10, ...,  7,  7, 11])

In [71]:
def generate_stats(df):
    counts = np.array(count_nodes_per_cascade(df))
    print("Average Number of Nodes Activated: {}".format(np.average(counts)))
    print("Standard Deviation of Number of Nodes Activated: {}".format(np.std(counts)))
    print("Maximum Time Activated: {}".format(max(df.max())))

In [72]:
generate_stats(df_lib)
print("------------------")
generate_stats(df_con)
print("------------------")
generate_stats(df_ndp)
print("------------------")
generate_stats(df_lgbt)
print("------------------")
generate_stats(df_bloc)

Average Number of Nodes Activated: 9.24875124875125
Standard Deviation of Number of Nodes Activated: 1.4982710445503513
Maximum Time Activated: 3.0
------------------
Average Number of Nodes Activated: 3.195804195804196
Standard Deviation of Number of Nodes Activated: 0.5507440953508388
Maximum Time Activated: 3.0
------------------
Average Number of Nodes Activated: 4.431568431568431
Standard Deviation of Number of Nodes Activated: 0.838367209511711
Maximum Time Activated: 3.0
------------------
Average Number of Nodes Activated: 3.2397602397602396
Standard Deviation of Number of Nodes Activated: 0.6403495100041694
Maximum Time Activated: 3.0
------------------
Average Number of Nodes Activated: 6.8551448551448555
Standard Deviation of Number of Nodes Activated: 1.129035554229047
Maximum Time Activated: 3.0