# Information Cascade Analysis

In [48]:
import pandas as pd
from functools import reduce

## Identifying Important Bridges
Go through each cascade experiment and see if there are any strong,regular, or weak bridges that were impacted during the cascade

In [2]:
strong_df = pd.read_csv('../Community Analysis/Strong_Bridges.csv')
strong_df

,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Id,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,225,0.0,4.0,196717787,NaN,NaN,alexboulerice,Alexandre,Boulerice,NDP,0.076489,8.155527e+05,2.0,0.000223,0.007819,6
1,222,0.0,4.0,215632349,NaN,NaN,CharlieAngusNDP,Charlie,Angus,NDP,0.245437,4.958324e+06,2.0,0.000335,0.042220,6
2,1574,4.0,NaN,596787864,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.000000,1

In [3]:
reg_df = pd.read_csv('../Community Analysis/Regular_Bridges.csv')

In [4]:
weak_df = pd.read_csv('../Community Analysis/Weak_Bridges.csv')

### Liberal Cascade

In [8]:
lib_df =  pd.read_csv('liberal_Information_Cascade.csv')
lib_df = lib_df.rename(columns={"id":"Id"})
lib_df

                      Id  lib_average_activation_time
0               14705053                          1.0
1               14837621                          1.0
2               15391466                          2.0
3               16158419                          1.0
4               16213179                          1.0
..                   ...                          ...
442  1442076364501180423                          2.0
443  1442426176287346696                          2.0
444  1444654432453529609                          2.0
445  1445583571985469450                          1.0
446  1446352422272528385                          1.0

[447 rows x 2 columns]

#### Strong Bridges

In [9]:
strong_lib = pd.merge(lib_df, strong_df, on="Id")

In [10]:
strong_lib

,Id,lib_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,596787864,1.0,1574,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1

#### Regular Bridges

In [11]:
reg_lib = pd.merge(lib_df, reg_df, on="Id")
reg_lib

Empty DataFrame
Columns: [Id, lib_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Weak Bridges

In [12]:
weak_lib = pd.merge(lib_df, weak_df, on="Id")
weak_lib

,Id,lib_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,16272844,1.0,1010,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.097217e+06,1.0,0.011728,0.000000,1
1,22849568,0.0,112,0.0,2.0,NaN,NaN,SeamusORegan,Seamus,O'Regan,Liberal,0.184197,2.048459e+06,1.0,0.000335,0.027477,6
2,40550119,1.0,130,0.0,2.0,NaN,NaN,Carolyn_Bennett,Carolyn,Bennett,Liberal,0.150814,1.614482e+06,1.0,0.000894,0.021557,6
3,61521038,1.0,149,0.0,2.0,NaN,NaN,karinagould,Karina,Gould,Liberal,0.090343,1.063783e+06,1.0,0.000112,0.016419,6
4,2891740872,0.0,152,0.0,2.0,NaN,NaN,HonAhmedHussen,Ahmed,Hussen,Liberal,0.100984,8.264850e+05,1.0,0.000335,0.013068,6
5,1446352422272528385,1.0,3071,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.781095e+06,1.0,0.005696,0.000000,1

### Conservative Cascade

In [13]:
con_df =  pd.read_csv('conservative_Information_Cascade.csv')
con_df = con_df.rename(columns={"id":"Id"})

#### Strong Bridges

In [14]:
strong_con = pd.merge(con_df, strong_df, on="Id")
strong_con

Empty DataFrame
Columns: [Id, con_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Regular Bridges

In [15]:
reg_con = pd.merge(con_df, reg_df, on="Id")
reg_con

,Id,con_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,711980580813066240,1.0,945,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,736622.894841,2.0,0.000782,0.0,1

#### Weak Bridges

In [16]:
weak_con = pd.merge(con_df, weak_df, on="Id")
weak_con

,Id,con_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,1086084557009575936,0.0,81,NaN,2.0,NaN,NaN,AlexRuff17,Alex,Ruff,Conservative,0.056597,7.056699e+05,3.0,0.000000,0.008936,6
1,1446352422272528385,1.0,3071,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.781095e+06,1.0,0.005696,0.000000,1

### NDP Cascade

In [19]:
ndp_df =  pd.read_csv('ndp_Information_Cascade.csv')
ndp_df = ndp_df.rename(columns={"id":"Id"})

#### Strong Bridges

In [20]:
strong_ndp = pd.merge(ndp_df, strong_df, on="Id")
strong_ndp

,Id,ndp_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,196717787,0.0,225,0.0,4.0,NaN,NaN,alexboulerice,Alexandre,Boulerice,NDP,0.076489,8.155527e+05,2.0,0.000223,0.007819,6
1,215632349,1.0,222,0.0,4.0,NaN,NaN,CharlieAngusNDP,Charlie,Angus,NDP,0.245437,4.958324e+06,2.0,0.000335,0.042220,6
2,596787864,2.0,1574,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.000000,1

#### Regular Bridges

In [21]:
reg_ndp = pd.merge(ndp_df, reg_df, on="Id")
reg_ndp

Empty DataFrame
Columns: [Id, ndp_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Weak Bridges

In [22]:
weak_ndp = pd.merge(ndp_df, weak_df, on="Id")
weak_ndp

,Id,ndp_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,196717787,0.0,225,0.0,4.0,NaN,NaN,alexboulerice,Alexandre,Boulerice,NDP,0.076489,8.155527e+05,2.0,0.000223,0.007819,6
1,215632349,1.0,222,0.0,4.0,NaN,NaN,CharlieAngusNDP,Charlie,Angus,NDP,0.245437,4.958324e+06,2.0,0.000335,0.042220,6
2,2715275551,0.0,277,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Activist Organization,0.066483,6.853130e+05,2.0,0.000000,0.008712,3

### LGBTQ2S+ Cascade

In [23]:
lgbt_df =  pd.read_csv('LGBTQ2S_Information_Cascade.csv')
lgbt_df = lgbt_df.rename(columns={"id":"Id"})

#### Strong Bridges

In [24]:
strong_lgbt = pd.merge(lgbt_df, strong_df, on="Id")
strong_lgbt

,Id,lgbt_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,596787864,1.0,1574,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1

#### Regular Bridges

In [25]:
reg_lgbt = pd.merge(lgbt_df, reg_df, on="Id")
reg_lgbt

Empty DataFrame
Columns: [Id, lgbt_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Weak Bridges

In [26]:
weak_lgbt = pd.merge(lgbt_df, weak_df, on="Id")
weak_lgbt

,Id,lgbt_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon
0,119925381,0.0,253,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Activist Organization,0.061598,1.397821e+06,5.0,0.0,0.012063,3

### Bloc Cascade

In [27]:
bloc_df =  pd.read_csv('bloc_Information_Cascade.csv')
bloc_df = bloc_df.rename(columns={"id":"Id"})

#### Strong Bridges

In [28]:
strong_bloc = pd.merge(bloc_df, strong_df, on="Id")
strong_bloc

Empty DataFrame
Columns: [Id, bloc_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Regular Bridges

In [29]:
reg_bloc = pd.merge(bloc_df, reg_df, on="Id")
reg_bloc

Empty DataFrame
Columns: [Id, bloc_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

#### Weak Bridges

In [30]:
weak_bloc = pd.merge(bloc_df, weak_df, on="Id")
weak_bloc

Empty DataFrame
Columns: [Id, bloc_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon]
Index: []

## Inter Community Interaction in Cascades

In [34]:
nodes = pd.read_csv("../Community Analysis/nodes_with_community_connection_info.csv")

In [41]:
def find_comm_interaction(df, nodes,name):
    inter_comm = pd.merge(df, nodes, on="Id")
    inter_comm = inter_comm[inter_comm['community'] != name]
    return inter_comm

In [65]:
def cascade_node_info(df, nodes,name):
    inter_comm = pd.merge(df, nodes, on="Id")
    return inter_comm

In [66]:
lib_com = find_comm_interaction(lib_df, nodes, "Liberal")
lib = cascade_node_info(lib_df, nodes, "")
con = cascade_node_info(con_df, nodes, "")
bloc = cascade_node_info(bloc_df, nodes, "")
lgbt = cascade_node_info(lgbt_df, nodes, "")
ndp = cascade_node_info(ndp_df, nodes, "")

In [51]:
con_com = find_comm_interaction(con_df, nodes, "Conservative")

In [45]:
ndp_com = find_comm_interaction(ndp_df, nodes, "NDP")
ndp_com

,Id,ndp_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon,id,community
8,16213179,1.0,1239,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.325127e+05,1.0,0.000447,0.0,1,16213179,Liberal
51,78429753,1.0,4817,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.030634e+04,5.0,0.000223,0.0,1,78429753,LGBTQ2S+
55,86861008,1.0,1986,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,9.144622e+03,1.0,0.000223,0.0,1,86861008,Liberal
66,122053347,2.0,4434,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,6.475376e+04,3.0,0.000335,0.0,1,122053347,Conservative
99,276093811,1.0,4571,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,9.134286e+04,4.0,0.000447,0.0,1,276093811,Bloc QuÃ©bÃ©cois
104,291336460,1.0,925,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,7.534409e+02,1.0,0.000335,0.0,1,291336460,Liberal
148,596787864,2.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1,596787864,Liberal
152,760497115,1.0,4572,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,4.0,0.000112,0.0,1,760497115,Bloc QuÃ©bÃ©cois
175,1483413924,1.0,1846,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,7.624746e+02,1.0,0.000335,0.0,1,1483413924,Liberal
192,2275886439,1.0,4573,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.920029e+04,4.0,0.000447,0.0,1,2275886439,Bloc QuÃ©bÃ©cois
194,2292642554,2.0,4435,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.433778e+04,3.0,0.000223,0.0,1,2292642554,Conservative
197,2434162616,1.0,130,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.198769e+06,1.0,0.003686,0.0,1,2434162616,Liberal
199,2557859383,2.0,92,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.132692e+06,1.0,0.003127,0.0,1,2557859383,Liberal
220,3187125694,2.0,2147,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.569898e+04,1.0,0.000335,0.0,1,3187125694,Liberal
230,4819639768,1.0,4575,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,5.0,0.000112,0.0,1,4819639768,LGBTQ2S+
260,971857794826567680,1.0,1358,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,6.125972e+04,1.0,0.000558,0.0,1,971857794826567680,Liberal
273,1066847336050147329,1.0,4570,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.941750e+05,4.0,0.001452,0.0,1,1066847336050147329,Bloc QuÃ©bÃ©cois
287,1178019071821877250,2.0,4431,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.279598e+05,3.0,0.001005,0.0,1,1178019071821877250,Conservative
307,1299517391240671233,2.0,1845,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.618907e+04,1.0,0.000335,0.0,1,1299517391240671233,Liberal
315,1329460132967821314,1.0,4569,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.987478e+04,3.0,0.000223,0.0,1,1329460132967821314,Conservative
331,1408262420640960512,2.0,4429,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.385965e+04,3.0,0.000223,0.0,1,1408262420640960512,Conservative
336,1430883215439540230,2.0,4430,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.537520e+04,3.0,0.000223,0.0,1,1430883215439540230,Conservative
339,1439240496921161733,1.0,4574,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,3.689728e+02,4.0,0.000447,0.0,1,1439240496921161733,Bloc QuÃ©bÃ©cois

In [46]:
bloc_com = find_comm_interaction(bloc_df, nodes, "Bloc QuÃ©bÃ©cois")
bloc_com

,Id,bloc_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon,id,community
2,16213179,2.0,1239,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,232512.703618,1.0,0.000447,0.0,1,16213179,Liberal
188,1171742672614113282,1.0,6416,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,13806.008781,3.0,0.000335,0.0,1,1171742672614113282,Conservative
216,1384365976922181637,1.0,3224,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,88676.276989,3.0,0.000447,0.0,1,1384365976922181637,Conservative

In [47]:
lgbt_com = find_comm_interaction(lgbt_df, nodes, "LGBTQ2S+")
lgbt_com

,Id,lgbt_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon,id,community
4,17174462,2.0,4467,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,17174462,NDP
6,21426717,2.0,4470,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,21426717,NDP
21,58340767,1.0,85,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,7.338912e+04,1.0,0.000894,0.000000,1,58340767,Liberal
23,67758676,2.0,4462,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,67758676,NDP
39,225067116,2.0,4452,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,225067116,NDP
53,486703473,2.0,4454,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,486703473,NDP
64,577727470,1.0,8114,1.0,1.0,NaN,NaN,NaN,NaN,NaN,Activist Organization,0.034501,3.735905e+05,2.0,0.000112,0.005026,3,577727470,NDP
68,596787864,1.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.000000,1,596787864,Liberal
81,1223950760,1.0,4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.266123e+06,1.0,0.007148,0.000000,1,1223950760,Liberal
90,1548315212,2.0,4461,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1548315212,NDP
93,1650588223,2.0,4481,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1650588223,NDP
96,2262304373,1.0,142,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,2.091874e+05,1.0,0.000447,0.000000,1,2262304373,Liberal
98,2367303485,2.0,4466,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,2367303485,NDP
133,753744536887824385,1.0,3756,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.340788e+05,2.0,0.000447,0.000000,1,753744536887824385,NDP
134,776153719675072512,2.0,4473,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,776153719675072512,NDP
136,787738985481240576,2.0,4459,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,787738985481240576,NDP
154,1024397417423106048,2.0,4475,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1024397417423106048,NDP
163,1115838887623122954,1.0,660,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.538537e+05,1.0,0.001564,0.000000,1,1115838887623122954,Liberal
172,1260759194833006593,2.0,4468,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1260759194833006593,NDP
173,1260770767123312640,2.0,4484,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1260770767123312640,NDP
176,1346317368637603841,2.0,4228,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1.819404e+04,2.0,0.000335,0.000000,1,1346317368637603841,NDP
182,1378038493105037320,2.0,4479,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1378038493105037320,NDP
187,1416921060788801539,2.0,4453,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000e+00,2.0,0.000112,0.000000,1,1416921060788801539,NDP

https://stackoverflow.com/questions/44327999/python-pandas-merge-multiple-dataframes

In [67]:
data_frames = [lib, con, ndp, bloc, lgbt]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)

In [68]:
df_merged

Empty DataFrame
Columns: [lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, ndp_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, bloc_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, Id, lgbt_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon, id, community]
Index: []

[0 rows x 91 columns]

In [69]:
data_frames = [lib, con, ndp, lgbt]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, ndp_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, Id, lgbt_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 73 columns]

In [70]:
data_frames = [lib, con, ndp, bloc]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, ndp_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, Id, bloc_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 73 columns]

In [71]:
data_frames = [lib, lgbt, ndp, bloc]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [Id, lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, lgbt_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, ndp_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, bloc_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 73 columns]

In [72]:
data_frames = [lib, con, lgbt, bloc]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, lgbt_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, Id, bloc_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 73 columns]

In [73]:
data_frames = [ndp, con, lgbt, bloc]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [ndp_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, lgbt_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, Id, bloc_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 73 columns]

In [77]:
bloc

,Id,bloc_average_activation_time,Unnamed: 0,Source Comm Interaction Count,Target Comm Interaction Count,Label,timeset,twittername,first name,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon,id,community
0,12220452,1.0,7660,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,68.712151,4.0,0.000223,0.000000,1,12220452,Bloc QuÃ©bÃ©cois
1,16014404,0.0,7454,0.0,1.0,NaN,NaN,sbergeron,StÃ©phane,Bergeron,Bloc QuÃ©bÃ©cois,0.078522,255072.588278,4.0,0.000447,0.008154,6,16014404,Bloc QuÃ©bÃ©cois
2,16213179,2.0,1239,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,232512.703618,1.0,0.000447,0.000000,1,16213179,Liberal
3,16450356,1.0,7687,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000,4.0,0.000112,0.000000,1,16450356,Bloc QuÃ©bÃ©cois
4,17721863,1.0,7507,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,5428.066729,4.0,0.001005,0.000000,1,17721863,Bloc QuÃ©bÃ©cois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,1435677654699675654,3.0,7753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,47.546973,4.0,0.000223,0.000000,1,1435677654699675654,Bloc QuÃ©bÃ©cois
226,1437734637531504644,1.0,7656,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,0.000000,4.0,0.000112,0.000000,1,1437734637531504644,Bloc QuÃ©bÃ©cois
227,1439240496921161733,1.0,4574,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,368.972818,4.0,0.000447,0.000000,1,1439240496921161733,Bloc QuÃ©bÃ©cois
228,1440532151582134272,1.0,7628,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,318.470570,4.0,0.000447,0.000000,1,1440532151582134272,Bloc QuÃ©bÃ©cois
229,1440664285210767367,1.0,7600,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003877,1203.676016,4.0,0.000447,0.000000,1,1440664285210767367,Bloc QuÃ©bÃ©cois

In [75]:
data_frames = [lib, ndp, con]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [Id, lib_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, ndp_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y, con_average_activation_time, Unnamed: 0, Source Comm Interaction Count, Target Comm Interaction Count, Label, timeset, twittername, first name, last name, political affiliation, influence, betweenness_centrality, communityid, out_degree_centrality, in_degree_centrality, polygon, id, community]
Index: []

[0 rows x 55 columns]

In [76]:
data_frames = [bloc, con]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

Empty DataFrame
Columns: [Id, bloc_average_activation_time, Unnamed: 0_x, Source Comm Interaction Count_x, Target Comm Interaction Count_x, Label_x, timeset_x, twittername_x, first name_x, last name_x, political affiliation_x, influence_x, betweenness_centrality_x, communityid_x, out_degree_centrality_x, in_degree_centrality_x, polygon_x, id_x, community_x, con_average_activation_time, Unnamed: 0_y, Source Comm Interaction Count_y, Target Comm Interaction Count_y, Label_y, timeset_y, twittername_y, first name_y, last name_y, political affiliation_y, influence_y, betweenness_centrality_y, communityid_y, out_degree_centrality_y, in_degree_centrality_y, polygon_y, id_y, community_y]
Index: []

[0 rows x 37 columns]

In [78]:
data_frames = [lib, ndp, lgbt]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,lib_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name,political affiliation,influence,betweenness_centrality,communityid,out_degree_centrality,in_degree_centrality,polygon,id,community
0,596787864,1.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1,596787864,Liberal

In [80]:
data_frames = [lib, ndp]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,lib_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name_y,political affiliation_y,influence_y,betweenness_centrality_y,communityid_y,out_degree_centrality_y,in_degree_centrality_y,polygon_y,id_y,community_y
0,16213179,1.0,1239,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,2.325127e+05,1.0,0.000447,0.0,1,16213179,Liberal
1,596787864,1.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1,596787864,Liberal
2,1483413924,2.0,1846,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,7.624746e+02,1.0,0.000335,0.0,1,1483413924,Liberal
3,2434162616,1.0,130,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.198769e+06,1.0,0.003686,0.0,1,2434162616,Liberal
4,2557859383,1.0,92,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.132692e+06,1.0,0.003127,0.0,1,2557859383,Liberal
5,3313678069,1.0,510,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.413873e+05,2.0,0.000447,0.0,1,3313678069,NDP
6,971857794826567680,1.0,1358,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,6.125972e+04,1.0,0.000558,0.0,1,971857794826567680,Liberal
7,1265853916077527042,1.0,1373,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,2.420734e+04,2.0,0.000335,0.0,1,1265853916077527042,NDP
8,1297554634182209537,1.0,2695,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,7.722538e+03,2.0,0.000223,0.0,1,1297554634182209537,NDP
9,1415746394871189504,2.0,2554,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.118865e+05,2.0,0.000558,0.0,1,1415746394871189504,NDP

In [81]:
data_frames = [lib, lgbt]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,lib_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name_y,political affiliation_y,influence_y,betweenness_centrality_y,communityid_y,out_degree_centrality_y,in_degree_centrality_y,polygon_y,id_y,community_y
0,596787864,1.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1,596787864,Liberal
1,1223950760,1.0,4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.266123e+06,1.0,0.007148,0.0,1,1223950760,Liberal
2,1115838887623122954,1.0,660,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.538537e+05,1.0,0.001564,0.0,1,1115838887623122954,Liberal

In [82]:
data_frames = [ndp, lgbt]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,ndp_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name_y,political affiliation_y,influence_y,betweenness_centrality_y,communityid_y,out_degree_centrality_y,in_degree_centrality_y,polygon_y,id_y,community_y
0,596787864,2.0,5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.321371e+06,1.0,0.001899,0.0,1,596787864,Liberal
1,1346317368637603841,2.0,4228,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.819404e+04,2.0,0.000335,0.0,1,1346317368637603841,NDP

In [83]:
data_frames = [con, lib]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,con_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name_y,political affiliation_y,influence_y,betweenness_centrality_y,communityid_y,out_degree_centrality_y,in_degree_centrality_y,polygon_y,id_y,community_y
0,823933874551959552,2.0,1375,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,1.953440e+04,3.0,0.000447,0.0,1,823933874551959552,Conservative
1,1446352422272528385,1.0,167,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,3.781095e+06,1.0,0.005696,0.0,1,1446352422272528385,Liberal

In [84]:
data_frames = [ndp, con]

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Id'],
                                            how='inner'), data_frames)
df_merged

,Id,ndp_average_activation_time,Unnamed: 0_x,Source Comm Interaction Count_x,Target Comm Interaction Count_x,Label_x,timeset_x,twittername_x,first name_x,last name_x,...,last name_y,political affiliation_y,influence_y,betweenness_centrality_y,communityid_y,out_degree_centrality_y,in_degree_centrality_y,polygon_y,id_y,community_y
0,818660875259277313,2.0,4205,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,99684.303627,2.0,0.000558,0.0,1,818660875259277313,NDP
1,1178019071821877250,2.0,4431,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003877,227959.782013,3.0,0.001005,0.0,1,1178019071821877250,Conservative